### ISSUE TITLE
model structure failed

### ISSUE THREAD

**Issue by syu-tan** [ChargedMonk/Social-Distancing-using-YOLOv5#2] opened 2020-08-24 04:56 UTC
i run `detect.py`  next happend 

```File "detect.py", line 166, in <module>
    detect()
  File "detect.py", line 62, in detect
    pred = model(img, augment=opt.augment)[0]
  File "/Users/s-yasui/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/s-yasui/Documents/ai/pytorch/Social-Distancing-using-YOLOv5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/Users/s-yasui/Documents/ai/pytorch/Social-Distancing-using-YOLOv5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/Users/s-yasui/anaconda3/envs/yolov5/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/Users/s-yasui/Documents/ai/pytorch/Social-Distancing-using-YOLOv5/models/yolo.py", line 28, in forward
    x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
RuntimeError: shape '[1, 3, 85, 56, 80]' is invalid for input of size 573440
```
tensor size is correct ?

**Comment by ChargedMonk** [comment] 2020-08-24 06:51
@syu-tan could you tell me which weight file did you use. Also, could you tell me the exact command which you used to run the detect.py script?

**Comment by DexterFernandes** [comment] 2020-08-25 14:41
@ChargedMonk I got the same error when I tried running detect.py

I ran the `detect.py` script with the yolov5s weights and the yolov5m weights.

`python detect.py --source /home/dexter/ML/test_video.avi --weights='yolov5s.pt'`

error:
File "detect.py", line 166, in <module>
    detect()
  File "detect.py", line 62, in detect
    pred = model(img, augment=opt.augment)[0]
  File "/home/dexter/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/home/dexter/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 28, in forward
    x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
RuntimeError: shape '[1, 3, 85, 48, 80]' is invalid for input of size 491520

`python detect.py --source /home/dexter/ML/test_video.avi --weights='yolov5m.pt`

error:
File "detect.py", line 166, in <module>
    detect()
  File "detect.py", line 62, in detect
    pred = model(img, augment=opt.augment)[0]
  File "/home/dexter/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 91, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 108, in forward_once
    x = m(x)  # run
  File "/home/dexter/anaconda3/envs/torch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/dexter/ML/LNS/social_distancing/Social-Distancing-using-YOLOv5/models/yolo.py", line 28, in forward
    x[i] = x[i].view(bs, self.na, self.no, ny, nx).permute(0, 1, 3, 4, 2).contiguous()
RuntimeError: shape '[1, 3, 85, 48, 80]' is invalid for input of size 737280

**Comment by ChargedMonk** [comment] 2020-08-25 21:40
@syu-tan, @DexterFernandes I tried different videos (including different formats and sizes) but was not able to reproduce this error. Are you both sure that the right dependencies are installed? If video sharing is not possible, can you tell me if this error is for some specific video types or specific yolov5 weights, or does it throw the same error for all weights and videos?

**Comment by DexterFernandes** [comment] 2020-08-26 07:50
@ChargedMonk I have installed all dependencies and I have tested with the yolov5s and yolov5m models. I have tested with the .avi and .mp4 video formats and I am getting the same error as earlier. The same error shows up no matter what model I use.

**Comment by ChargedMonk** [comment] 2020-08-26 10:28
@DexterFernandes I've resolved the issue now. I think one of the commits introduced this bug, but now I've tested and committed the files and it should work for all of you. In case there's still an issue, please point out. Thanks.

**Comment by DexterFernandes** [comment] 2020-08-26 10:41
Thanks @ChargedMonk 

I will test once again and I will get back to you.

**Comment by syu-tan** [comment] 2020-08-30 05:23
@ChargedMonk 
Thank you !
i pulled, but i occur same error.
i used command that is 'python detect.py --yolov5m.pt` 
of course, i have installed requirements.txt

**Comment by ChargedMonk** [comment] 2020-09-01 18:08
@syu-tan, this should not be the case, I tested the script again on colab - [notebook](https://colab.research.google.com/drive/16Tm5H6GcohHDgwmul-UitBtv3bRshJ3B?usp=sharing) and it was working fine for me. I need more details on your issue.

**Closed as completed** 2021-06-23 18:41 UTC
